# The type of RC
string rc_type

# switch A state
RcSwitchState switch_swa

# switch B state
RcSwitchState switch_swb

# switch C state
RcSwitchState switch_swc

# switch D state
RcSwitchState switch_swd

# Right stick vertical axis
int8 stick_right_y

# Right stick horizontal axis
int8 stick_right_x

# Left stick vertical axis
int8 stick_left_y

# Left stick horizontal axis
int8 stick_left_x

# The state of the buttons
int8 buttons
