name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Limit jobs run by PRs or branches by cancelling ongoing jobs
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-and-the-default-behavior
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}

    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
